apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 50
        zipkin:
          address: jaeger-collector.istio-system.svc.cluster.local:9411
    accessLogFile: "/dev/stdout"
    accessLogEncoding: "JSON"

