repositories:
- name: cilium
  url: https://helm.cilium.io

releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.16.1
  # 以下は必須ではない
  values:
  - k8sServiceHost: "192.168.11.100" # Control Planeのホスト名またはIPアドレス
  - k8sServicePort: "6443"
  - hubble:
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - icmp
        - http
  - ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.0.0.0/16"] # CIRDはあくまで一例
  - socketLB:
      enabled: true
      hostNamespaceOnly: true
  - cni:
      exclusive: false
  - l2announcements:
      enabled: true
  - k8sClientRateLimit:
      qps: 10
      burst: 20
  - kubeProxyReplacement: true
  - sctp:
      enabled: true
  - tcFilterPriority: 100

