apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-for-kiali
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - gw-for-http
  http:
  - match:
    - uri:
        prefix: /kiali
    route:
    - destination:
        port:
          number: 20001
        host: kiali

